### ISSUE TITLE
tokens

### ISSUE THREAD

**Issue by SeanFarris** [batarlton/ml-project#1]
Not a big deal, but in the future don't upload tokens to github (what we use to connect to twitter). They're supposed to be private, so the idea would be to store the tokens in an encrypted local file. 

Anyone can access this page and see our tokens.

**Comment by crounial** [comment]
Good point lol sorry

**Comment by crounial** [comment]
Got rid of them but they're still in the commit history. We can create new credentials and store them on a local file like you said if it would make you more comfortable. We are currently pulling the tweets to a local file so we don't keep hitting our search request limit from Twitter API.

**Comment by SeanFarris** [comment]
Like I said, not a big deal. I'll be deleting that account once the project is over anyhow.  I would leave it, but it's tied to one of my phone numbers and one of my email addresses.

**Comment by crounial** [comment]
Oh I thought that you were using the app specific credentials and not a personal twitter account. I should have looked it over more closely.
